# -*- coding: utf-8 -*-
"""CronaAnimatedMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NVqdjMocvuL8L1Q2AOH2feWQV4cgjLaR
"""

#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly as py
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs


#import dataset 
df = pd.read_csv('/covid_19_clean_complete.csv')
df.dtypes

#data preprocessing
df = df.rename(columns = {'Country/Region' : 'Country'})
df_countries = df.groupby(['Country', 'Date']).sum().reset_index().sort_values('Date', ascending = False)
df_countries = df_countries.drop_duplicates( subset = ['Country'])
df_countries = df_countries[df_countries['Confirmed']>0]

df_countrydate = df[df['Confirmed']>0]
df_countrydate = df_countrydate.groupby(['Date', 'Country']).sum().reset_index()


#making static graph
fig = go.Figure(data= go.Choropleth(locations = df_countries['Country'], locationmode = 'country names', 
                                    z = df_countries['Confirmed'], colorscale = 'Reds',
                                    marker_line_color = 'Black', marker_line_width = 0.4))

fig.update_layout(title_text = 'WorldWide ases as of 5th April 2020', title_x = 0.5,
                  geo=dict(showframe = True, showcoastlines = False, projection_type = 'equirectangular'))

fig

#animated graph

fig2 = px.choropleth(df_countrydate, locations="Country", locationmode= "country names", color = "Confirmed", hover_name="Country",
                     animation_frame = "Date")

fig2.update_layout(title_text = "Spread of Coronavirus", title_x = 0.5, geo = dict(showframe= True, showcoastlines= False))

fig2